2024-11-26 06:36:46,218 - backend.flask_api.app - INFO - Starting application in development mode
2024-11-26 06:36:47,561 - backend.flask_api.app - INFO - Starting application in development mode
2025-01-04 12:32:04,287 - backend.flask_api.app - INFO - Application paths configured successfully
2025-01-04 12:32:04,288 - backend.flask_api.app - INFO - CORS initialized successfully
2025-01-04 12:32:04,288 - backend.flask_api.app - INFO - JWT initialized successfully
2025-01-04 12:32:04,357 - backend.flask_api.app - ERROR - Database initialization error: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\end-2-end-data-pipeline\backend\backend\flask_api\app\__init__.py", line 145, in _init_database
    engine, SessionLocal = init_db(app)
                           ^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\end-2-end-data-pipeline\backend\backend\database\config.py", line 46, in init_db
    Base.metadata.create_all(bind=engine)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\sql\schema.py", line 5868, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3252, in _run_ddl_visitor
    with self.begin() as conn:
         ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3242, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-04 12:32:04,461 - backend.flask_api.app - ERROR - Failed to create application: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\end-2-end-data-pipeline\backend\backend\flask_api\app\__init__.py", line 314, in create_app
    engine, SessionLocal = _init_database(app)
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\end-2-end-data-pipeline\backend\backend\flask_api\app\__init__.py", line 145, in _init_database
    engine, SessionLocal = init_db(app)
                           ^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\end-2-end-data-pipeline\backend\backend\database\config.py", line 46, in init_db
    Base.metadata.create_all(bind=engine)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\sql\schema.py", line 5868, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3252, in _run_ddl_visitor
    with self.begin() as conn:
         ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3242, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\pypoetry\Cache\virtualenvs\backend-mncTA70r-py3.12\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)
